### ISSUE TITLE
[FIX] 변경된 요구사항 반영 

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#112]
## 📝 개요
9월 22일 ~ 23일에 발생한 요구사항을 반영한다. 

## ✅ TODO

- [x] 게시글 목록 응답에 writerEmail 추가
- [x] 정렬 동작 확인 : ASC 작동 안되고 있음
- [x] pdf 응답 보내기 
- [x] pdf 응답 s3 연동 된 환경에서 잘 작동되는지 확인
