### ISSUE TITLE
[REFACT] boards 테이블 쓰던 방식을 enum으로 변경

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#165]
## 📝 개요
새로운 게시글 카테고리를 만들려고 했는데, 
기존의 db에서 id 자동 생성 쓰던 방법으로는 board id 기준으로 url을 매핑하는 것이 직관성이 떨어진다고 생각이 들었음.
그래서 리팩토링 하고자 함

## ✅ TODO

- [ ] boardType enum 클래스 생성 
- [ ] /boards : 게시판 관련 API 수정, 로직 변경
- [ ] boards 테이블 삭제 및 기존 id로 넣은거 변경 하는 쿼리문 추가  V2__delete_board_update_post.sql
## 💬 기타
- postCreateRequest 에서 boardId 주던거 boardType으로 줘야함 
- "카테고리별 게시글 목록"

**Comment by S2uJeong** [comment]
기존의 틀을 유지하며 수정하기로 함
