### ISSUE TITLE
[FEAT] 과제 CRUD 하는 관리자 기능 

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#188]
## ✅ TODO
- [ ] Controller/Service 분리 : AdminHomeworkr, AdminHomeworkReply, Homework
- [ ] representativeHomework table 생성 
- [ ] 과제 CRUD
- [ ] 과제 대표 id에 따라 조회되게끔 서비스 로직 변경
