### ISSUE TITLE
[REFACTOR] POST 기능 고도화

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#27]
## ✅ TODO
- [x] board - post 설계 구상
- [x] post 카테고리별 controller 분리  -> 다시 통합
- [x] post 작성은 학생이상 권한만 가능하게 로직 수정 (등업 게시판 제외)
- [x] post Entity에 댓글 개수를 나타내는 commentCount 필드 추가 
- [x] post에 파일 첨부 가능하도록 변경 (등업 게시판 제외)
