### ISSUE TITLE
[BUILD] 프로덕션 환경 구축

### ISSUE THREAD

**Issue by cheon4050** [team-abcdedu/abcdedu-backend#35]
## 📝 개요
프로덕션 환경 구축

## ✅ TODO

- [x] aws 프로덕션 배포
- [x] 테라폼 dev,prod 분리
- [x] cicd-prod 환경 구축
