### ISSUE TITLE
[FEAT] 게시판, 카테고리 기능 

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#4]
## 📝 개요
게시판(Post), 게시판 카테고리(Board) 기능 

## ✅ TODO
- [x] 연관 엔티티 생성 및 연관관계 추가 
- [x] API 공통 반환 클래스 생성
- [x] 게시판, 카테고리 CRUD 제작
