### ISSUE TITLE
[FEAT] 공통 과제(Problem) 기능

### ISSUE THREAD

**Issue by S2uJeong** [team-abcdedu/abcdedu-backend#51]
## 📝 개요
- 해당 기능은 내용의 변동이 없을 예정이라, 질문을 DB에 저장해 놓고 응답 생성/조회만을 구현한다. 

## ✅ TODO

- [ ] Problem ERD 작성 및 Problem Entity 코드작성
- [ ] Database에 쿼리 작성해서 채워 넣기
- [ ] ProblemReply C, R 기능 구현
