### ISSUE TITLE
[FEAT] 클래스 기능 추가

### ISSUE THREAD

**Issue by cheon4050** [team-abcdedu/abcdedu-backend#61]
## 📝 개요
클래스 기능 수정 및 추가

## ✅ TODO
- [ ] 서브 클래스 별 자료 등록 추가
- [ ] 서브클래스 프로젝트, 실습 제거
- [ ] 이론, 시험 수정 기능 추가
